name: Demo Workflow

on:
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  demo-job:
    name: Demo Job
    runs-on: ubunto-latest
    steps:
      - name: Message 1
        run: echo "This is message 1"
      - name: Message 2
        run: echo "This is message 2"
